import { SVGProps } from '../../node_modules/react';
export type SVGIconProps = {} & SVGProps<SVGSVGElement>;
export declare function SunIcon({ strokeWidth, ...rest }: SVGIconProps): import("react").JSX.Element;
export declare function MoonIcon({ strokeWidth, ...rest }: SVGIconProps): import("react").JSX.Element;
export declare function ComputerIcon({ strokeWidth, ...rest }: SVGIconProps): import("react").JSX.Element;
export declare function Square({ strokeWidth, ...rest }: SVGIconProps): import("react").JSX.Element;
export declare function SquareCheck({ strokeWidth, ...rest }: SVGIconProps): import("react").JSX.Element;
export declare function Circle({ strokeWidth, ...rest }: SVGIconProps): import("react").JSX.Element;
export declare function CircleCheck({ strokeWidth, ...rest }: SVGIconProps): import("react").JSX.Element;
export declare function Spinner({ strokeWidth, className, ...rest }: SVGIconProps): import("react").JSX.Element;
