import { Meta, StoryObj } from "@storybook/react";
import { expect, within } from "storybook/test";
import { PiMagnifyingGlass } from "react-icons/pi";
import { availableColors, availableSizes } from "@/types";
import { AutocompleteInput, Input, InputProps } from "./index";

const meta: Meta<typeof Input> = {
  title: "Components/Input",
  tags: ["autodocs"],
  component: Input,
  decorators: (Story) => (
    <div className="storybookContainer">
      <Story />
    </div>
  ),
  argTypes: {
    placeholder: { table: { category: "storybook" } },
    color: {
      control: { type: "select" },
      options: availableColors,
      table: { category: "controls" },
    },
    size: {
      control: { type: "inline-radio" },
      table: { category: "controls" },
    },
    type: { table: { category: "controls" } },
    label: { table: { category: "controls" } },
    disabled: { table: { category: "controls" } },
    error: { table: { category: "controls" } },
    showRevealPasswordButton: {
      if: { arg: "type", eq: "password" },
      table: { category: "controls" },
    },
    startIcon: { control: false, table: { category: "docs" } },
    endIcon: { control: false, table: { category: "docs" } },
    labelClassName: { control: false, table: { category: "docs" } },
    wrapperClassName: { control: false, table: { category: "docs" } },
    errorClassName: { control: false, table: { category: "docs" } },
    inputContainerClassName: { control: false, table: { category: "docs" } },
    wrapperStyle: { control: false, table: { category: "docs" } },
    as: { control: false, table: { category: "docs" } },
    ref: { control: false, table: { category: "docs" } },
    inputContainerStyle: { control: false, table: { category: "docs" } },
    stepUpAriaLabel: { control: false, table: { category: "docs" } },
    stepDownAriaLabel: { control: false, table: { category: "docs" } },
    revealPasswordToggleAriaLabel: {
      control: false,
      table: { category: "docs" },
    },
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

const countries = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo (Democratic Republic of the)",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (Democratic People's Republic of)",
  "Korea (Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia (the former Yugoslav Republic of)",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China[a]",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United States of America",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const Default: Story = {
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByTestId("default");
    await expect(button, "renders").toBeTruthy();
  },
  render: (props) => {
    return <Input data-testid="default" {...props} />;
  },
  args: {
    placeholder: "Input",
  },
};

export const WithLabel: Story = {
  render: (props) => {
    return <Input {...props} />;
  },
  args: {
    placeholder: "Input",
    label: "Label",
  },
  argTypes: {
    startIcon: { table: { disable: true } },
    endIcon: { table: { disable: true } },
    labelClassName: { table: { disable: true } },
    wrapperClassName: { table: { disable: true } },
    errorClassName: { table: { disable: true } },
    inputContainerClassName: { table: { disable: true } },
    wrapperStyle: { table: { disable: true } },
    as: { table: { disable: true } },
    ref: { table: { disable: true } },
    inputContainerStyle: { table: { disable: true } },
    stepUpAriaLabel: { table: { disable: true } },
    stepDownAriaLabel: { table: { disable: true } },
    revealPasswordToggleAriaLabel: { table: { disable: true } },
  },
};

export const WithIcon: Story = {
  render: (props) => {
    return <Input {...props} />;
  },
  args: {
    startIcon: <PiMagnifyingGlass />,
    placeholder: "Input",
    label: "Label",
  },
  argTypes: {
    startIcon: { table: { disable: true } },
    endIcon: { table: { disable: true } },
    labelClassName: { table: { disable: true } },
    wrapperClassName: { table: { disable: true } },
    errorClassName: { table: { disable: true } },
    inputContainerClassName: { table: { disable: true } },
    wrapperStyle: { table: { disable: true } },
    as: { table: { disable: true } },
    ref: { table: { disable: true } },
    inputContainerStyle: { table: { disable: true } },
    stepUpAriaLabel: { table: { disable: true } },
    stepDownAriaLabel: { table: { disable: true } },
    revealPasswordToggleAriaLabel: { table: { disable: true } },
  },
};

export const WithError: Story = {
  render: (props) => {
    return <Input {...props} />;
  },
  args: {
    startIcon: <PiMagnifyingGlass />,
    placeholder: "Input",
    label: "Label",
    error: "Error",
  },
  argTypes: {
    startIcon: { table: { disable: true } },
    endIcon: { table: { disable: true } },
    labelClassName: { table: { disable: true } },
    wrapperClassName: { table: { disable: true } },
    errorClassName: { table: { disable: true } },
    inputContainerClassName: { table: { disable: true } },
    wrapperStyle: { table: { disable: true } },
    as: { table: { disable: true } },
    ref: { table: { disable: true } },
    inputContainerStyle: { table: { disable: true } },
    stepUpAriaLabel: { table: { disable: true } },
    stepDownAriaLabel: { table: { disable: true } },
    revealPasswordToggleAriaLabel: { table: { disable: true } },
  },
};

export const Textarea: Story = {
  render: (props) => {
    return <Input as="textarea" {...props} />;
  },
  args: {
    placeholder: "Input",
    label: "Label",
  },
  argTypes: {
    startIcon: { table: { disable: true } },
    endIcon: { table: { disable: true } },
    labelClassName: { table: { disable: true } },
    wrapperClassName: { table: { disable: true } },
    errorClassName: { table: { disable: true } },
    inputContainerClassName: { table: { disable: true } },
    wrapperStyle: { table: { disable: true } },
    as: { table: { disable: true } },
    ref: { table: { disable: true } },
    inputContainerStyle: { table: { disable: true } },
    stepUpAriaLabel: { table: { disable: true } },
    stepDownAriaLabel: { table: { disable: true } },
    revealPasswordToggleAriaLabel: { table: { disable: true } },
  },
};

export const Number: Story = {
  render: (props) => {
    return <Input {...props} />;
  },
  args: {
    type: "number",
    placeholder: "Input",
    label: "Label",
  },
  argTypes: {
    type: { table: { disable: true } },
    startIcon: { table: { disable: true } },
    endIcon: { table: { disable: true } },
    labelClassName: { table: { disable: true } },
    wrapperClassName: { table: { disable: true } },
    errorClassName: { table: { disable: true } },
    inputContainerClassName: { table: { disable: true } },
    wrapperStyle: { table: { disable: true } },
    as: { table: { disable: true } },
    ref: { table: { disable: true } },
    inputContainerStyle: { table: { disable: true } },
    stepUpAriaLabel: { table: { disable: true } },
    stepDownAriaLabel: { table: { disable: true } },
    revealPasswordToggleAriaLabel: { table: { disable: true } },
  },
};

export const Password: Story = {
  render: (props) => {
    return <Input {...props} />;
  },
  args: {
    type: "password",
    placeholder: "Input",
    label: "Label",
    revealPasswordToggleAriaLabel: "Reveal",
  },
  argTypes: {
    type: { table: { disable: true } },
    startIcon: { table: { disable: true } },
    endIcon: { table: { disable: true } },
    labelClassName: { table: { disable: true } },
    wrapperClassName: { table: { disable: true } },
    errorClassName: { table: { disable: true } },
    inputContainerClassName: { table: { disable: true } },
    wrapperStyle: { table: { disable: true } },
    as: { table: { disable: true } },
    ref: { table: { disable: true } },
    inputContainerStyle: { table: { disable: true } },
    stepUpAriaLabel: { table: { disable: true } },
    stepDownAriaLabel: { table: { disable: true } },
    revealPasswordToggleAriaLabel: { table: { disable: true } },
  },
};

export const Disabled: Story = {
  render: (props) => {
    return <Input disabled {...props} />;
  },
  args: {
    startIcon: <PiMagnifyingGlass />,
    placeholder: "Input",
    label: "Label",
  },
  argTypes: {
    disabled: { table: { disable: true } },
    startIcon: { table: { disable: true } },
    endIcon: { table: { disable: true } },
    labelClassName: { table: { disable: true } },
    wrapperClassName: { table: { disable: true } },
    errorClassName: { table: { disable: true } },
    inputContainerClassName: { table: { disable: true } },
    wrapperStyle: { table: { disable: true } },
    as: { table: { disable: true } },
    ref: { table: { disable: true } },
    inputContainerStyle: { table: { disable: true } },
    stepUpAriaLabel: { table: { disable: true } },
    stepDownAriaLabel: { table: { disable: true } },
    revealPasswordToggleAriaLabel: { table: { disable: true } },
  },
};

export const WithAutocomplete: Story = {
  render: ({ ...rest }) => {
    return <AutocompleteInput items={countries} {...(rest as InputProps)} />;
  },
  args: {
    startIcon: <PiMagnifyingGlass />,
    placeholder: "Search countries",
    label: "Country",
  },
  argTypes: {
    startIcon: { table: { disable: true } },
    endIcon: { table: { disable: true } },
    labelClassName: { table: { disable: true } },
    wrapperClassName: { table: { disable: true } },
    errorClassName: { table: { disable: true } },
    inputContainerClassName: { table: { disable: true } },
    wrapperStyle: { table: { disable: true } },
    as: { table: { disable: true } },
    ref: { table: { disable: true } },
    inputContainerStyle: { table: { disable: true } },
    stepUpAriaLabel: { table: { disable: true } },
    stepDownAriaLabel: { table: { disable: true } },
    revealPasswordToggleAriaLabel: { table: { disable: true } },
  },
};

export const Sizes: Story = {
  render: (props) => {
    return (
      <div className="grid gap-4">
        {availableSizes.map((size) => {
          return <Input {...props} key={size} label={size} size={size} />;
        })}
      </div>
    );
  },
  args: {
    startIcon: <PiMagnifyingGlass />,
    placeholder: "Input",
  },
  argTypes: {
    size: { table: { disable: true } },
    label: { table: { disable: true } },
    disabled: { table: { disable: true } },
    startIcon: { table: { disable: true } },
    endIcon: { table: { disable: true } },
    labelClassName: { table: { disable: true } },
    wrapperClassName: { table: { disable: true } },
    errorClassName: { table: { disable: true } },
    inputContainerClassName: { table: { disable: true } },
    wrapperStyle: { table: { disable: true } },
    as: { table: { disable: true } },
    ref: { table: { disable: true } },
    inputContainerStyle: { table: { disable: true } },
    stepUpAriaLabel: { table: { disable: true } },
    stepDownAriaLabel: { table: { disable: true } },
    revealPasswordToggleAriaLabel: { table: { disable: true } },
  },
};

export const Colors: Story = {
  render: (props) => {
    return (
      <>
        {availableColors.map((color) => {
          return <Input {...props} key={color} label={color} color={color} />;
        })}
      </>
    );
  },
  args: {
    startIcon: <PiMagnifyingGlass />,
    placeholder: "Input",
  },
  argTypes: {
    color: { table: { disable: true } },
    label: { table: { disable: true } },
    disabled: { table: { disable: true } },
    startIcon: { table: { disable: true } },
    endIcon: { table: { disable: true } },
    labelClassName: { table: { disable: true } },
    wrapperClassName: { table: { disable: true } },
    errorClassName: { table: { disable: true } },
    inputContainerClassName: { table: { disable: true } },
    wrapperStyle: { table: { disable: true } },
    as: { table: { disable: true } },
    ref: { table: { disable: true } },
    inputContainerStyle: { table: { disable: true } },
    stepUpAriaLabel: { table: { disable: true } },
    stepDownAriaLabel: { table: { disable: true } },
    revealPasswordToggleAriaLabel: { table: { disable: true } },
  },
};
